# vim: syntax=python tabstop=2 expandtab
# coding: utf-8
configfile: '../config/config.yaml'

include: 'rules/taxa.smk'
include: 'rules/traits.smk'
include: 'rules/annotations.smk'

rule all:
  input:
    '../results/taxa.done',
    '../results/traits.done',
    '../results/annotations.done'
