# vim: syntax=python tabstop=2 expandtab
# coding: utf-8
configfile: '../config/config.yaml'

include: 'rules/col.smk'
include: 'rules/annotations.smk'

rule all:
  input:
    '../results/annotations.done'
