# vim: syntax=yaml tabstop=2 expandtab
# coding: utf-8

# Catalogue of Life (CoL) settings
col_taxa_file_path: '../resources/col/latest_dwca/Taxon.tsv'
col_taxa_arthropoda: '../results/col/Taxon_arthro.tsv'
col_taxa_arthropoda_sm: '../results/col/Taxon_arthro_sm.tsv'

# PLAZI settings
plazi_root_dir: '../resources/plazi/'
plazi_xml_dir: '../resources/plazi/plazi.xml/'
plazi_arthro_xml_dir: '../resources/plazi/plazi_arthro.xml/'
plazi_arthro_txt_dir: '../resources/plazi/plazi_arthro.txt/'
plazi_arthro_id_doi: '../resources/plazi/plazi_arthro_id_doi.csv'
plazi_arthro_pmc_xml: '../resources/plazi/pmc_xml/'
plazi_arthro_doi_pmid_map: '../resources/plazi/doi_pmid.csv'
plazi_arthro_doi_pmid: '../resources/plazi/plazi_arthro_id_doi_pmid.csv'
plazi_pmc_txt_dir: '../resources/plazi/pmc_txt/'
plazi_pmc_txt_fmt_dir: '../resources/plazi/pmc_txt_formatted/'
