# vim: syntax=yaml tabstop=2 expandtab
# coding: utf-8

# Catalogue of Life (CoL) settings
col_data_dir: '../resources/col/latest_dwca'
col_taxa_file: '../resources/col/latest_dwca/Taxon.tsv'
col_taxa_arthropoda: '../results/col/Taxon_arthro.tsv'
col_version_file: '../resources/col/latest_dwca.zip.version'

# Encyclopedia of Life (EOL) settings
eol_data_dir: '../resources/eol/trait_bank'
eol_taxa_file: '../resources/eol/trait_bank/pages.csv'
eol_version_file: '../resources/eol/traits_all.zip.version'

# Taxa output files
col_eol_taxa: '../results/col_eol_taxa.tsv'
